apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gbx89hism-go 
  janus-idp.io/tekton: gbx89hism-go
  backstage.io/kubernetes-id: gbx89hism-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gbx89hism-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  