apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gbx89hism-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gbx89hism-go 
  name: gbx89hism-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gbx89hism-go 
